export const data = [
    {
        id:1,
        img:"images/author/imag-03.jpg",
        name:"vohoangtrung",
        number:999999
    },
    {
        id:2,
        img:"images/author/imag-04.jpg",
        name:"vohoangtrung",
        number:999999
    },
    {
        id:3,
        img:"images/author/imag-05.jpg",
        name:"vohoangtrung",
        number:999999
    },
    {
        id:4,
        img:"images/author/imag-06.jpg",
        name:"vohoangtrung",
        number:999999
    },
    {
        id:5,
        img:"images/author/imag-07.jpg",
        name:"vohoangtrung",
        number:999999
    },
    {
        id:6,
        img:"images/author/imag-08.jpg",
        name:"vohoangtrung",
        number:999999
    },
    {
        id:7,
        img:"images/author/imag-02.jpg",
        name:"vohoangtrung",
        number:999999
    },
]